FROM colmedo/reactapp

COPY . .

# Environment variables
ENV NODE_ENV production

RUN yarn install && yarn global add mocha 

RUN export JUNIT_REPORT_PATH=./report.xml
RUN ls -alh

CMD ["yarn", "testjunit"]
#CMD mocha test --reporter mocha-xunit-reporter