FROM node:alpine3.10

RUN mkdir -p /app
WORKDIR /app

COPY package.json /
COPY yarn.lock /

RUN yarn install && yarn global add mocha && yarn add mocha-jenkins-reporter

COPY . /

EXPOSE 3000

# Environment variables
ENV NODE_ENV test

RUN export JUNIT_REPORT_PATH=./report.xml

CMD ["yarn", "testmocha"]