FROM colmedo/reactapp

COPY test test

# Environment variables
ENV NODE_ENV production

RUN yarn install && yarn global add mocha && yarn add mocha-xunit-reporter 

#RUN export JUNIT_REPORT_PATH=./report.xml
RUN ls -alh

CMD ["yarn", "testxunit"]